# Machine Learning and Statistics - Task 1

These are my solution to the Task 1 Assessment The author
 is Babu Baskaran
****

#### Task 1: Calculate Square Root of 2

We can calculate the square root of two using Newton's method [1], [2],[3], [4],[5],[6]

To find the square root 2, we can iterate using the following equation

$$ z = z - \frac{z^2 - x} {2z} $$




[1] A Tour of Go; Exercise: Loops and Functions https://tour.golang.org/flowcontrol/8

[2] Floating Point Limitations https://docs.python.org/3.4/tutorial/floatingpoint.html 

[3] How to use Python exponents with ** operator https://kodify.net/python/math/exponents/

[4] Wikipedia,"Different methods of Finding Square root of 2"  https://en.wikipedia.org/wiki/Square_root_of_2

[5] "Finding square root of 2 with 100 decimal places" https://stackoverflow.com/questions/8505385/finding-square-root-of-2-upto-more-than-100-decimal-places
[6] Newton's Method to find Square Root https://en.wikipedia.org/wiki/Newton%27s_method


In [1]:
def sqrt2(num):
    
    
    """ A function to calculate the square root of number 2
    """
    
    # Intial value of the square root of z1
    z1 = (num * 1.0) / 2
    
    # Inital value of the square root of z2
    z2 = (z1 + (num / z1) / 2)
    
    # Loop for to run until the value of z1 - z2 is less than 0.00001
    while abs(z1 - z2) > 0.00001:
        
        z1 = z2
        
        z2 = (z1 + (num / z1)) / 2
  
        # format given value with 100 decimal place
        y = format(z2, ',.100f')
        
    # Return the square root of 2        
    return y
sqrt2(2)

'1.4142135623746898698271934335934929549694061279296875000000000000000000000000000000000000000000000000'

## Tests of the function

We are testing the function with some known values

In [2]:
# Test the function on 25
sqrt2(25)

'5.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'

In [3]:
# Test the function on 2.
sqrt2(2)

'1.4142135623746898698271934335934929549694061279296875000000000000000000000000000000000000000000000000'

The floating value has limitation with decimal, due to the fact after I formatted the value into 100 decimal it gives zeros after 50th decimal.

In [4]:
import math
math.sqrt(2)

1.4142135623730951

Since the float decimal limitations we are converting the float value into string and returning the results.



In [5]:
def sqrtnew():
     
    """ A function to calculate the square root of number 2
    """
    # Assign the value of num with 2
    num = 2
    
    # Multiplying num by 100 and finding exponential(power) of that value 

    S = num * 100 ** 100
    
    # Finding Floor Division of S 
    new = S//2
    
    #Loop for to run until the value of S minus exponential of 2 is less than 0
    while S - (new**2) < 0:
        # assigning value of new plus Floor Division of S which is again floor divison of 2
        new = (new + S//new)//2

    # changing the float into string by doing this we are able to get the square root of 2 mutiplied by 100**100
    new = (str(new))
    
    # Return square root of 2 by concatenating 2 string values
    # Return zero will bring the 1 character of the result and return 1: will bring the rest of the result from position 1 till the end
      
    
    return(new[0] + "." + new[1:])
    
sqrtnew()

'1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727'

## Tests of the function

We are testing the function(the number 2 is the value which is given already on the code) so its generate the answer for the same

In [6]:
sqrtnew()

'1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727'

In [7]:
import decimal
decimal.getcontext().prec=101
decimal.Decimal("2").sqrt()

Decimal('1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727')

# Machine Learning and Statistics - Task 2

Task 2: Chi-squared test for independence

[1],[2],[3],[4]

Chi-Square Test for Independence https://stattrek.com/chi-square-test/independence.aspx
Calculate Chi Square Statistic by Hand https://www.statisticssolutions.com/non-parametric-analysis-chi-square/
Chi Square Statistic Video https://www.youtube.com/watch?v=LE3AIyY_cn8
Chi Squared Test Wikipedia https://en.wikipedia.org/wiki/Chi-squared_test
Chi Square test SciPy.org https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chisquare.html

Two-Way Tables and the Chi-Square Test http://www.stat.yale.edu/Courses/1997-98/101/chisq.htm

Scipy.stats.chi2_contingency https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2_contingency.html

Contingency table (also known as a cross tabulation or crosstab) https://en.wikipedia.org/wiki/Contingency_table

Chi-square statistic for hypothesis testing https://www.khanacademy.org/math/ap-statistics/chi-square-tests/chi-square-goodness-fit/v/chi-square-statistic?modal=1

Statistics : Chi-suared test https://pythonhealthcare.org/2018/04/13/58-statistics-chi-squared-test/
By using chi2_contingency we are able to find the Chi-squared value is 24.6 and the p value is 0.0004098425861096696






$$ x^2 = \sum_ \frac{f(o) - f(e)} {f(e)} $$



The sample data has 3 rows and 4 coloumns





In [1]:
from scipy.stats import chisquare
chisquare([16, 18, 16, 14, 12, 12])

Power_divergenceResult(statistic=2.0, pvalue=0.8491450360846096)

In [2]:
chisquare([16, 18, 16, 14, 12, 12], f_exp=[16, 16, 16, 16, 16, 8])

Power_divergenceResult(statistic=3.5, pvalue=0.6233876277495822)

In [4]:
import numpy as np
obs = np.array([[16, 18, 16, 14, 12, 12], [32, 24, 16, 28, 20, 24]]).T
obs.shape

chisquare(obs)

Power_divergenceResult(statistic=array([2.        , 6.66666667]), pvalue=array([0.84914504, 0.24663415]))

In [5]:
#By setting axis=None, the test is applied to all data in the array, which is equivalent to applying the test to the flattened array.
chisquare(obs, axis=None)


chisquare(obs.ravel())

Power_divergenceResult(statistic=23.310344827586206, pvalue=0.01597569253412758)

We can use the same and change the array to our data

In [21]:
SData = np.array([[90, 60, 104, 95], [30, 50, 51, 20], [30, 40, 45, 35]]).T
SData.shape

chisquare(SData)

Power_divergenceResult(statistic=array([12.50143266, 18.56291391,  3.33333333]), pvalue=array([5.84876294e-03, 3.36606536e-04, 3.43030146e-01]))

In [28]:
# A two-way example (2x3)

from scipy.stats import chi2_contingency
obs = np.array([[10, 10, 20], [20, 20, 20]])
chi2_contingency(obs)

g, p, dof, expctd = chi2_contingency(obs, lambda_="log-likelihood")
g, p, dof, expctd

(2.768858761678132, 0.25046668010954165, 2, array([[12., 12., 16.],
        [18., 18., 24.]]))

In [31]:
# A four-way example (2 x 2 x 2 x 2):

# chi2 : float The test statistic
# p : float The p-value of the test
# dof : int Degrees of freedom
# expected : ndarray, same shape as observed (The expected frequencies, based on the mariginal sums of the table)
obs = np.array(
    [[[[12, 17],
       [11, 16]],
      [[11, 12],
       [15, 16]]],
     [[[23, 15],
       [30, 22]],
      [[14, 17],
       [15, 16]]]])
chi2_contingency(obs)

g, p, dof, expctd = chi2_contingency(obs, lambda_="log-likelihood")
g, p

(8.829648779331881, 0.6376130295973088)

In [2]:
import numpy as np
import pandas as pd
import scipy.stats as stats

cols = ['A', 'B', 'C', 'D']
data = pd.DataFrame(columns=cols)

data.loc['White Collar'] = [90, 60, 104, 95]
data.loc['Blue Collar'] = [30, 50, 51, 20]
data.loc['No collar'] = [30, 40, 45, 35]

print(data)

V, p, dof, expected = stats.chi2_contingency(data) 
# add correction=False for uncorrected Chi-square

print ('P value for effect of area on proportion of each collar:')
print (p)
print ('\nExpected numbers if area did not effect proportion of each collar:')
print (expected)
print(V)
print(dof)

               A   B    C   D
White Collar  90  60  104  95
Blue Collar   30  50   51  20
No collar     30  40   45  35
P value for effect of area on proportion of each collar:
0.0004098425861096696

Expected numbers if area did not effect proportion of each collar:
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]
24.5712028585826
6


The Value of Chi-squared is 24.6 is accurate and I have identified this by doing the same manually with the following 2 formulas.

1) Define Null and Alternative Hypotheses

2) State Alph alpha = 0.05

3) Calculate Degrees of Freedom

df = (rows-1)(columns-2)
df=(3-1)(4-1)
df=(2)(3)=6

4) State Decision Rule

Using Chi Square Table we can get the value is 12.5916

If $X^2$ is greater than 12.5916, reject Ho

5) Calculate Test Statistic

$$ x^2 = \sum_ \frac{f(o) - f(e)} {f(e)} $$

fe = fcfr / n


# Machine Learning and Statistics - Task 3

Task 3: The standard deviation of an array of numbers



In [3]:
a = np.array([[1, 2], [3, 4]])
np.std(a)

np.std(a, axis=0)

np.std(a, axis=1)

array([0.5, 0.5])

In [5]:
a = np.zeros((2, 512*512), dtype=np.float32)
a[0, :] = 1.0
a[1, :] = 0.1
np.std(a)
np.std(a, dtype=np.float64)

0.4499999992549418